version: '3.9'
services:
  review-cosmetic-web-admin:
    # image: nexus.slitigenz.io:4000/review-cosmetic-web-admin:latest
    build:
      context: .
    container_name: review-cosmetic-web-admin
    restart: always
    ports:
      - '11102:3000'
    deploy:
      replicas: 1
