const DEFAULT_PAGE = 1
const DEFAULT_PAGE_SIZE = 30

const UPPER_HEADER_HEIGHT = 80
const LOWER_HEADER_HEIGHT = 70

const EMAIL_REGEX = /^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/

export { DEFAULT_PAGE, DEFAULT_PAGE_SIZE, EMAIL_REGEX, LOWER_HEADER_HEIGHT, UPPER_HEADER_HEIGHT }
